title: Violin Repertoire
description: A live dataset of violin repertoire for the community!
theme: just-the-docs

color_scheme: copper

url: https://just-the-docs.github.io
logo: "/assets/images/logo-violin-repertoire-dataset.png"
favicon_ico: "/assets/images/favicon.ico"

